# Generated by Django 5.0.1 on 2024-02-05 07:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0022_remove_faqdestination_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='media/banners/')),
                ('card_image', models.FileField(blank=True, null=True, upload_to='media/cards/')),
                ('priority_number', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Parent Destinations',
                'ordering': ('parent_name',),
            },
        ),
        migrations.CreateModel(
            name='FAQDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='max 255 characters', max_length=255)),
                ('answer', ckeditor.fields.RichTextField(blank=True, help_text='max 3000 characters', max_length=3000, null=True)),
                ('priority_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
                ('parent_destination', models.ForeignKey(blank=True, help_text='The Parent destination brings together all destinations with multilingual content but same location and common FAQ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_destinations', to='destinations.parentdestination')),
            ],
            options={
                'verbose_name': 'Frequently Asked Questions for Destination',
                'verbose_name_plural': 'Frequently Asked Questions for Destination',
                'db_table': 'faq_destination',
                'ordering': ('priority_number',),
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 60 characters, city name usually', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='max 60 characters, exactly url tail that is unique', max_length=60, unique=True)),
                ('page_title', models.CharField(blank=True, help_text='seo title for header in search list, max 120 characters', max_length=120, null=True)),
                ('page_description', models.TextField(blank=True, help_text='seo page description, max 500 characters', max_length=600, null=True)),
                ('keywords', models.TextField(blank=True, help_text='seo keywords', max_length=500, null=True)),
                ('main_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('main_subtitle', models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('introduction_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('introduction_subtitle', models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('introduction_text', ckeditor.fields.RichTextField(blank=True, help_text='max 6000 characters', max_length=6000, null=True)),
                ('short_introduction_text', models.CharField(blank=True, help_text='short text for recommendation cards, max 255 characters', max_length=255, null=True)),
                ('when_to_visit_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('when_to_visit_text', ckeditor.fields.RichTextField(blank=True, help_text='max 6000 characters', max_length=6000, null=True)),
                ('getting_around_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('getting_around_text', ckeditor.fields.RichTextField(blank=True, help_text='max 6000 characters', max_length=6000, null=True)),
                ('travel_tips_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('travel_tips_text', ckeditor.fields.RichTextField(blank=True, help_text='max 6000 characters', max_length=6000, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
                ('parent_destination', models.ForeignKey(blank=True, help_text='The Parent destination brings together all destinations with multilingual content but same location and common banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_destinations', to='destinations.parentdestination')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
