# Generated by Django 5.0.1 on 2024-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_all_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='recommendations_slogan',
            field=models.CharField(blank=True, help_text='max 120 characters, belong SEE MORE button', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='recommendations_subtitle',
            field=models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='recommendations_title',
            field=models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True),
        ),
    ]
