# Generated by Django 5.0.1 on 2024-04-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0008_alter_tagattraction_icon_img'),
        ('destinations', '0005_destination_top_attractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='top_attractions',
            field=models.ManyToManyField(related_name='top_attractions', to='attractions.attraction'),
        ),
    ]
