# Generated by Django 5.0.1 on 2024-04-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_alter_destination_top_attractions'),
        ('products', '0051_remove_experience_recommended_experiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='recommended_experiences',
            field=models.ManyToManyField(related_name='recommended', to='products.experience'),
        ),
    ]
