# Generated by Django 5.0.1 on 2024-04-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_destination_recommended_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='be_interested_destinations',
            field=models.ManyToManyField(to='destinations.destination'),
        ),
    ]
