# Generated by Django 5.0.1 on 2024-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_destination_be_interested_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentdestination',
            name='show_on_home_page',
            field=models.BooleanField(default=False, help_text='Include in the top Destinations on the home page'),
        ),
    ]
