# Generated by Django 5.0.1 on 2024-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_parentdestination_show_on_home_page'),
        ('products', '0054_alter_experience_experience_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='recommended_experiences',
            field=models.ManyToManyField(blank=True, related_name='recommended', to='products.experience'),
        ),
    ]
