# Generated by Django 5.0.1 on 2024-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0011_alter_attraction_recommendations_experiences'),
        ('destinations', '0010_alter_destination_recommended_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='be_interested_destinations',
            field=models.ManyToManyField(blank=True, to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='top_attractions',
            field=models.ManyToManyField(blank=True, related_name='top_attractions', to='attractions.attraction'),
        ),
    ]
