# Generated by Django 5.0.3 on 2024-05-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0013_alter_parentdestination_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqdestination',
            options={'ordering': ('-priority_number',), 'verbose_name': 'Frequently Asked Questions for Destination', 'verbose_name_plural': 'Frequently Asked Questions for Destination'},
        ),
    ]
