# Generated by Django 5.0.3 on 2024-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_alter_faqdestination_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='faq_subtitle',
            field=models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True),
        ),
    ]
