# Generated by Django 5.0.3 on 2024-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_alter_destination_faq_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentdestination',
            name='banner_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/banners/'),
        ),
        migrations.AddField(
            model_name='parentdestination',
            name='card_image_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/cards/'),
        ),
    ]
