services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin:/volume_pgadmin/

  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postfixadmin:
    image: analogic/postfixadmin
    environment:
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_NAME=postgres_db
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - postfixadmin_data:/var/www/html


volumes:
  pgadmin:
  redis:
  postfixadmin_data: