services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin:/volume_pgadmin/

  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data


volumes:
  pgadmin:
  redis: