# Generated by Django 5.0.1 on 2024-02-07 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_adults_count_and_more'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='stripe_checkout_session_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
