# Generated by Django 5.0.1 on 2024-02-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_rename_product_purchase_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='stripe_payment_id',
            new_name='stripe_payment_intent_id',
        ),
    ]
