# Generated by Django 5.0.1 on 2024-02-19 15:24

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0033_rename_price_currency_parentexperience_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ParentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('priority_number', models.IntegerField(blank=True, default=0, help_text='number for ordering in list on page by default', null=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='media/banners/')),
                ('card_image', models.FileField(blank=True, null=True, upload_to='media/cards/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('parent_name',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='max 60 characters, exactly url tail that is unique', max_length=200, unique=True)),
                ('page_title', models.CharField(blank=True, help_text='seo title for header in search list, max 120 characters', max_length=120, null=True)),
                ('page_description', models.TextField(blank=True, help_text='seo page description, max 500 characters', max_length=600, null=True)),
                ('keywords', models.TextField(blank=True, help_text='seo keywords', max_length=500, null=True)),
                ('title', models.CharField(help_text='160 characters, max', max_length=160)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='30000 characters, max', max_length=30000, null=True)),
                ('views', models.IntegerField(default=0)),
                ('read_time', models.IntegerField(default=0)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
                ('categories', models.ManyToManyField(to='blogs.category')),
                ('parent_blog', models.ForeignKey(blank=True, help_text='The Parent Blog brings together all blogs with multilingual content but same context and common banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_blogs', to='blogs.parentblog')),
            ],
            options={
                'ordering': ('-date_published',),
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
