# Generated by Django 5.0.1 on 2024-03-31 15:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.CreateModel(
            name='BlockBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='title of text block including within Blog, max 255 characters', max_length=255, null=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, help_text='maximum length of text block 3000 characters', max_length=3000, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blogs.blog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
