# Generated by Django 5.0.1 on 2024-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_content_blockblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='middle_picture',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/middle_pictures'),
        ),
    ]
