# Generated by Django 5.0.3 on 2024-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_slug'),
        ('products', '0078_alter_parentexperience_child_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='experience_recommendations',
            field=models.ManyToManyField(blank=True, to='products.experience'),
        ),
        migrations.AddField(
            model_name='blog',
            name='recommendations_slogan',
            field=models.CharField(blank=True, help_text='max 160 characters, belong SEE MORE button', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='recommendations_subtitle',
            field=models.CharField(blank=True, help_text='max 500 characters', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='recommendations_title',
            field=models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True),
        ),
    ]
