# Generated by Django 5.0.3 on 2024-05-17 11:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockblog',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='maximum length of text block 20000 characters', max_length=20000, null=True),
        ),
    ]
