# Generated by Django 5.0.3 on 2024-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blockblog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='middle_picture_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/middle_pictures'),
        ),
        migrations.AddField(
            model_name='parentblog',
            name='banner_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/banners/'),
        ),
        migrations.AddField(
            model_name='parentblog',
            name='card_image_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/cards/'),
        ),
    ]
