# Generated by Django 5.0.1 on 2024-02-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=220, null=True)),
                ('name', models.CharField(blank=True, help_text='Card name', max_length=120, null=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_city', models.CharField(blank=True, max_length=160, null=True)),
                ('address_country', models.CharField(blank=True, max_length=2, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=160, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=160, null=True)),
                ('address_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address_state', models.CharField(blank=True, max_length=60, null=True)),
                ('shipping_address_city', models.CharField(blank=True, max_length=160, null=True)),
                ('shipping_address_country', models.CharField(blank=True, max_length=2, null=True)),
                ('shipping_address_line1', models.CharField(blank=True, max_length=160, null=True)),
                ('shipping_address_line2', models.CharField(blank=True, max_length=160, null=True)),
                ('shipping_address_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping_address_state', models.CharField(blank=True, max_length=60, null=True)),
                ('shipping_address_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('shipping_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_name', models.CharField(blank=True, max_length=160, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
