# Generated by Django 5.0.1 on 2024-02-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address_email',
        ),
    ]
