# Generated by Django 5.0.1 on 2024-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shipping_address_country',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
