# Generated by Django 5.0.1 on 2024-03-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address_city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address_country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address_line1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address_line2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address_postal_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_address_state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_phone',
        ),
    ]
