# Generated by Django 5.0.1 on 2024-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_shipping_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_country',
            field=models.CharField(blank=True, help_text='max 2 characters, for example: UK, DE', max_length=2, null=True),
        ),
    ]
