# Generated by Django 5.0.3 on 2024-05-09 11:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0012_alter_destination_slug'),
        ('products', '0076_remove_experience_traveler_tips_text_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The name of the landing page, views in main header', max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='The content of the landing page, max 20 000 characters', max_length=20000, null=True)),
                ('slug', models.SlugField(blank=True, help_text='max 255 characters, exactly url tail that is unique', max_length=255, unique=True)),
                ('page_title', models.CharField(blank=True, help_text='seo title for header in search list, max 255 characters', max_length=255, null=True)),
                ('page_description', models.TextField(blank=True, help_text='seo page description, max 500 characters', max_length=600, null=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='media/banners/')),
                ('card_image', models.FileField(blank=True, null=True, upload_to='media/cards/')),
                ('priority_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_navbar', models.BooleanField(default=False, help_text='Include in the navbar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.experiencecategory')),
                ('destination', models.ForeignKey(blank=True, help_text='The destination of the landing page. Should be empty for parent page where all destinations are available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.destination')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
            ],
            options={
                'ordering': ('title',),
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
