# Generated by Django 5.0.3 on 2024-05-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='related_landing_pages',
            field=models.ManyToManyField(blank=True, to='landing_pages.landingpage'),
        ),
    ]
