# Generated by Django 5.0.3 on 2024-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_alter_destination_slug'),
        ('landing_pages', '0003_landingpage_title_related_landing_pages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ('-priority_number', 'title')},
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='destination',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='destinations.destination'),
        ),
    ]
