# Generated by Django 5.0.3 on 2024-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0004_alter_landingpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='priority_number',
            field=models.IntegerField(blank=True, default=0, help_text='The higher the value of the priority number, the higher it appears in the list', null=True, verbose_name='Priority'),
        ),
    ]
