# Generated by Django 5.0.3 on 2024-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blockblog_text'),
        ('landing_pages', '0005_alter_landingpage_priority_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='blogs',
            field=models.ManyToManyField(blank=True, to='blogs.blog'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='blogs_title',
            field=models.CharField(blank=True, help_text='Title above Featured Articles section, max 255 characters', max_length=255, null=True, verbose_name='Featured Articles Title'),
        ),
    ]
