# Generated by Django 5.0.3 on 2024-05-23 19:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0006_landingpage_blogs_landingpage_blogs_title'),
        ('products', '0080_alter_parentexperience_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='max 255 characters', max_length=255)),
                ('answer', ckeditor.fields.RichTextField(blank=True, help_text='max 3000 characters', max_length=3000, null=True)),
                ('priority_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_landing_list', to='landing_pages.landingpage')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
            ],
            options={
                'verbose_name': 'Frequently Asked Questions for Landing Page',
                'verbose_name_plural': 'Frequently Asked Questions for Landing Page',
                'db_table': 'faq_landing_page',
                'ordering': ('-priority_number',),
            },
        ),
    ]
