# Generated by Django 5.0.3 on 2024-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0007_faqlandingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='faq_subtitle',
            field=models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='faq_title',
            field=models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True),
        ),
    ]
