# Generated by Django 5.0.3 on 2024-05-24 11:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0008_landingpage_faq_subtitle_landingpage_faq_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='seo_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='The content of the landing page between Featured Articles and FAQ, max 20 000 characters', max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='seo title for text block above FAQ, max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='The content under banner place, max 20 000 characters', max_length=20000, null=True),
        ),
    ]
