# Generated by Django 5.0.3 on 2024-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0009_landingpage_seo_text_landingpage_seo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='banner_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/banners/'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='card_image_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/cards/'),
        ),
    ]
