# Generated by Django 5.0.3 on 2024-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0010_landingpage_banner_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='menu_title',
            field=models.CharField(blank=True, help_text='The name of the landing page, views in menu list, 50 characters maximum', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='show_in_lisbon_things',
            field=models.BooleanField(default=False, help_text='Include in the menu lisbon things', verbose_name='Add to Lisbon Things to Do (Experience Type)'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='show_in_menu_our_services',
            field=models.BooleanField(default=False, help_text='Include in the menu our services', verbose_name='Add to Our Services'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='show_in_out_lisbon_things',
            field=models.BooleanField(default=False, help_text='Include in the menu out lisbon things', verbose_name='Add to Out Of Lisbon Things To Do (Destinations)'),
        ),
    ]
