# Generated by Django 5.0.3 on 2024-06-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0011_landingpage_menu_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ('-priority_number',)},
        ),
    ]
