# Generated by Django 5.0.1 on 2024-03-28 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='short_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='max 6000 characters', max_length=6000, null=True),
        ),
    ]
