# Generated by Django 5.0.1 on 2024-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_short_text_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show_on_home_page',
            field=models.BooleanField(default=False, help_text='Include in the top Reviews on the home page'),
        ),
    ]
