# Generated by Django 5.0.3 on 2024-05-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_options'),
        ('products', '0071_remove_product_free_cancellation_datetime'),
        ('reviews', '0005_review_show_on_home_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.experience'),
        ),
        migrations.AlterField(
            model_name='review',
            name='short_text',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.TextField(blank=True, help_text='max 320 characters', max_length=320, null=True)),
                ('show_on_home_page', models.BooleanField(default=True, help_text='Include in the top Reviews on the home page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent_experience',
        ),
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='review',
            name='show_on_home_page',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
