# Generated by Django 5.0.1 on 2024-04-04 11:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the page', max_length=60, unique=True)),
                ('slug', models.SlugField(help_text='Slug of the page, if blank, will be generated automatically from the title', unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='markdown content of the page, max 20 000 characters', max_length=20000, null=True)),
                ('page_title', models.CharField(blank=True, help_text='seo title for header in search list, max 120 characters', max_length=60, null=True)),
                ('page_description', models.TextField(blank=True, help_text='seo page description, max 500 characters', max_length=600, null=True)),
                ('keywords', models.TextField(blank=True, help_text='seo keywords', max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
