# Generated by Django 5.0.1 on 2024-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug of the page, if blank, will be generated automatically from the title, max 255 characters', max_length=255, null=True, unique=True),
        ),
    ]
