# Generated by Django 5.0.3 on 2024-05-03 08:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='markdown content of the page, max 50 000 characters', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='keywords',
            field=models.TextField(blank=True, help_text='SEO keywords', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_description',
            field=models.TextField(blank=True, help_text='SEO page description, max 500 characters', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(blank=True, help_text='SEO title for header in search list, max 120 characters', max_length=60, null=True),
        ),
    ]
