# Generated by Django 5.0.3 on 2024-05-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_value_tittle_ourvalues_value_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourvalues',
            options={'verbose_name_plural': 'our values'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'staff'},
        ),
    ]
