# Generated by Django 5.0.3 on 2024-05-31 16:08

import home.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_ourvalues_options_alter_staff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourvalues',
            name='icon_img',
            field=home.fields.SVGAndImageField(blank=True, null=True, upload_to='about_us/icons/'),
        ),
    ]
