# Generated by Django 5.0.3 on 2024-05-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_ourvalues_icon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourvalues',
            name='icon_img',
            field=models.FileField(blank=True, null=True, upload_to='about_us/icons/'),
        ),
    ]
