# Generated by Django 5.0.1 on 2024-02-02 15:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0019_delete_attraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('card_image', models.FileField(blank=True, null=True, upload_to='media/cards/')),
                ('slider_image_1', models.FileField(blank=True, null=True, upload_to='media/sliders/')),
                ('slider_image_2', models.FileField(blank=True, null=True, upload_to='media/sliders/')),
                ('slider_image_3', models.FileField(blank=True, null=True, upload_to='media/sliders/')),
                ('slider_image_4', models.FileField(blank=True, null=True, upload_to='media/sliders/')),
                ('slider_image_5', models.FileField(blank=True, null=True, upload_to='media/sliders/')),
                ('slider_image_6', models.FileField(blank=True, null=True, upload_to='media/sliders/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('parent_name',),
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 60 characters, city name usually', max_length=60)),
                ('priority_number', models.IntegerField(blank=True, default=0, help_text='number for ordering in list on page by default', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='max 60 characters, exactly url tail that is unique', max_length=60, unique=True)),
                ('page_title', models.CharField(blank=True, help_text='seo title for header in search list, max 120 characters', max_length=120, null=True)),
                ('page_description', models.TextField(blank=True, help_text='seo page description, max 500 characters', max_length=600, null=True)),
                ('keywords', models.TextField(blank=True, help_text='seo keywords', max_length=500, null=True)),
                ('introduction_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('introduction_text_above_slider', ckeditor.fields.RichTextField(blank=True, help_text='max 3000 characters', max_length=3000, null=True)),
                ('introduction_text_below_slider', ckeditor.fields.RichTextField(blank=True, help_text='max 3000 characters', max_length=3000, null=True)),
                ('short_introduction_text', models.CharField(blank=True, help_text='short text for recommendation cards, max 255 characters', max_length=255, null=True)),
                ('info_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('info_subtitle', models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('time_of_work', ckeditor.fields.RichTextField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('address', ckeditor.fields.RichTextField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('price', ckeditor.fields.RichTextField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('accessibility', ckeditor.fields.RichTextField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('possibility', ckeditor.fields.RichTextField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('recommendations_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('recommendations_subtitle', models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('recommendations_slogan', models.CharField(blank=True, help_text='max 120 characters, belong SEE MORE button', max_length=120, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
                ('parent_attraction', models.ForeignKey(blank=True, help_text='The Parent Attraction brings together all attractions with multilingual content but same location and common images.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_attractions', to='attractions.parentattraction')),
            ],
            options={
                'db_table': 'attractions',
                'ordering': ('priority_number', 'name'),
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
