# Generated by Django 5.0.1 on 2024-02-02 16:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('products', '0020_alter_parentdestination_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentattraction',
            options={'ordering': ('parent_name',), 'verbose_name': 'Parent Attraction', 'verbose_name_plural': 'Parent Attractions'},
        ),
        migrations.CreateModel(
            name='FAQAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='max 255 characters', max_length=255)),
                ('answer', ckeditor.fields.RichTextField(blank=True, help_text='max 3000 characters', max_length=3000, null=True)),
                ('priority_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
                ('parent_attraction', models.ForeignKey(blank=True, help_text='The Parent Attraction brings together all attractions with multilingual content but same location and common FAQ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_attractions', to='attractions.parentattraction')),
            ],
            options={
                'verbose_name': 'Frequently Asked Questions for Attractions',
                'verbose_name_plural': 'Frequently Asked Questions for Attractions',
                'db_table': 'faq_attractions',
                'ordering': ('priority_number',),
            },
        ),
    ]
