# Generated by Django 5.0.1 on 2024-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_alter_parentattraction_options_faqattraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='priority_number',
        ),
        migrations.AddField(
            model_name='parentattraction',
            name='priority_number',
            field=models.IntegerField(blank=True, default=0, help_text='number for ordering in list on page by default', null=True),
        ),
    ]
