# Generated by Django 5.0.1 on 2024-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_alter_attraction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='faq_subtitle',
            field=models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='faq_title',
            field=models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True),
        ),
    ]
