# Generated by Django 5.0.1 on 2024-02-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_remove_faqattraction_parent_attraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqattraction',
            name='attraction',
            field=models.ForeignKey(blank=True, help_text='The Parent Attraction brings together all attractions with multilingual content but same location and common FAQ.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attractions.attraction'),
        ),
    ]
