# Generated by Django 5.0.1 on 2024-03-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_alter_faqattraction_attraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to='attractions/icons/')),
                ('tag_name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='parentattraction',
            name='tags',
            field=models.ManyToManyField(to='attractions.tagattraction'),
        ),
    ]
