# Generated by Django 5.0.1 on 2024-03-31 15:27

import attractions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_tagattraction_parentattraction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagattraction',
            name='icon_img',
            field=models.ImageField(blank=True, help_text='Image in .svg supported.', null=True, upload_to=attractions.models.svg_upload_path),
        ),
    ]
