# Generated by Django 5.0.1 on 2024-04-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0008_alter_tagattraction_icon_img'),
        ('products', '0051_remove_experience_recommended_experiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='recommendations_experiences',
            field=models.ManyToManyField(to='products.experience'),
        ),
    ]
