# Generated by Django 5.0.1 on 2024-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0009_attraction_recommendations_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentattraction',
            name='show_on_home_page',
            field=models.BooleanField(default=False, help_text='Include in the top Attractions on the home page'),
        ),
    ]
