# Generated by Django 5.0.3 on 2024-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0012_alter_attraction_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentattraction',
            options={'ordering': ('-priority_number',), 'verbose_name': 'Parent Attraction', 'verbose_name_plural': 'Parent Attractions'},
        ),
        migrations.AlterField(
            model_name='parentattraction',
            name='priority_number',
            field=models.IntegerField(blank=True, default=0, help_text='The higher the value of the priority number, the higher it appears in the list', null=True, verbose_name='Priority'),
        ),
    ]
