# Generated by Django 5.0.3 on 2024-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0014_alter_attraction_faq_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentattraction',
            name='card_image_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/cards/'),
        ),
        migrations.AddField(
            model_name='parentattraction',
            name='slider_image_1_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/sliders/'),
        ),
        migrations.AddField(
            model_name='parentattraction',
            name='slider_image_2_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/sliders/'),
        ),
        migrations.AddField(
            model_name='parentattraction',
            name='slider_image_3_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/sliders/'),
        ),
        migrations.AddField(
            model_name='parentattraction',
            name='slider_image_4_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/sliders/'),
        ),
        migrations.AddField(
            model_name='parentattraction',
            name='slider_image_5_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/sliders/'),
        ),
        migrations.AddField(
            model_name='parentattraction',
            name='slider_image_6_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/sliders/'),
        ),
    ]
