# Generated by Django 5.0.3 on 2024-06-17 07:51

import attractions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0015_parentattraction_card_image_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagattraction',
            name='icon_img',
            field=models.FileField(blank=True, help_text='Image in .svg supported.', null=True, upload_to=attractions.models.svg_upload_path),
        ),
    ]
