name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.10'

      - name: Install dependencies
        run: |
          apt-get install -y binutils libgdal-dev
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python3 manage.py test

  build_and_push_docker_image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          docker build -t kivaschenko/portotours:$GITHUB_SHA .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push kivaschenko/portotours:$GITHUB_SHA

  deploy_to_digitalocean:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean Droplet
        run: |
          scp -o StrictHostKeyChecking=no deploy.sh root@164.90.170.238:/root/deploy.sh
          ssh -o StrictHostKeyChecking=no root@164.90.170.238 'bash -s' < /root/deploy.sh
