name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #      - name: Set up Python
      #        uses: actions/setup-python@v5
      #        with:
      #          python-version: '3.10'
      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils libgdal-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python3 manage.py test

  build_and_push_docker_image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t kivaschenko/portotours:latest .
          docker push kivaschenko/portotours:latest

  deploy_to_digitalocean:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          script: |
            docker pull kivaschenko/portotours:latest
            docker stop django-portotours || true
            docker rm django-portotours || true
            docker run -d --name django-portotours -p 8000:8000 kivaschenko/portotours:latest
