name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #      - name: Set up Python
      #        uses: actions/setup-python@v5
      #        with:
      #          python-version: '3.10'
      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils libgdal-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python3 manage.py test

  build_and_push_docker_image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t kivaschenko/portotours:latest .
          docker push kivaschenko/portotours:latest

  deploy_to_digitalocean:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          ssh-strict-host-key-checking: 'no'
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}
          ssh-agent-forwarding: 'yes'

      - name: Deploy to DigitalOcean Droplet
        run: |
          scp -v -o StrictHostKeyChecking=no deploy.sh root@164.90.170.238:~/deploy.sh
          ssh -v -o StrictHostKeyChecking=no root@164.90.170.238 'bash -s' < ~/deploy.sh
