# Generated by Django 5.0.1 on 2024-01-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_meetingpoint_auto_location_alter_meetingpoint_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoint',
            name='update_coords_by_geom',
            field=models.BooleanField(default=False, help_text='Automatically update longitude and latitude from map marker place.'),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='auto_location',
            field=models.BooleanField(default=True, help_text='After saving coordinates will be auto-defined by address'),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='country',
            field=models.CharField(blank=True, default='Portugal', help_text='Country name max 150 characters', max_length=150),
        ),
    ]
