# Generated by Django 5.0.1 on 2024-01-30 18:13

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_language_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='language',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max 60 characters, city name usually', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='max 60 characters, exactly url tail that is unique', max_length=60, unique=True)),
                ('page_title', models.CharField(blank=True, help_text='seo title for header in search list, max 120 characters', max_length=120, null=True)),
                ('page_description', models.TextField(blank=True, help_text='seo page description, max 500 characters', max_length=500, null=True)),
                ('keywords', models.TextField(blank=True, help_text='seo keywords', max_length=500, null=True)),
                ('main_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('main_subtitle', models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('introduction_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('introduction_subtitle', models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True)),
                ('introduction_text', models.TextField(blank=True, help_text='max 1000 characters', max_length=3000, null=True)),
                ('short_introduction_text', models.CharField(blank=True, help_text='short text for recommendation cards, max 255 characters', max_length=255, null=True)),
                ('when_to_visit_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('when_to_visit_text', models.TextField(blank=True, help_text='max 1000 characters', max_length=1000, null=True)),
                ('getting_around_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('getting_around_text', models.TextField(blank=True, help_text='max 1000 characters', max_length=1000, null=True)),
                ('travel_tips_title', models.CharField(blank=True, help_text='max 120 characters', max_length=120, null=True)),
                ('travel_tips_text', models.TextField(blank=True, help_text='max 2000 characters', max_length=2000, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'slug')},
            },
        ),
    ]
