# Generated by Django 5.0.1 on 2024-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_language_managers_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='getting_around_text',
            field=models.TextField(blank=True, help_text='max 2000 characters', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='introduction_text',
            field=models.TextField(blank=True, help_text='max 2000 characters', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='page_description',
            field=models.TextField(blank=True, help_text='seo page description, max 500 characters', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_tips_text',
            field=models.TextField(blank=True, help_text='max 6000 characters', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='when_to_visit_text',
            field=models.TextField(blank=True, help_text='max 2000 characters', max_length=1000, null=True),
        ),
    ]
