# Generated by Django 5.0.1 on 2024-01-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_destination_getting_around_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='abbreviation',
            new_name='code',
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('code', 'name')},
        ),
    ]
