# Generated by Django 5.0.1 on 2024-01-31 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_abbreviation_language_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='media/banners/')),
                ('card_image', models.FileField(blank=True, null=True, upload_to='media/cards/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('parent_name',),
            },
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, help_text='max 60 characters, exactly url tail that is unique', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='parent_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_destinations', to='products.parentdestination'),
        ),
    ]
