# Generated by Django 5.0.1 on 2024-02-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_parentdestination_alter_destination_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='getting_around_text',
            field=models.TextField(blank=True, help_text='max 6000 characters', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='introduction_text',
            field=models.TextField(blank=True, help_text='max 6000 characters', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='parent_destination',
            field=models.ForeignKey(blank=True, help_text='The Parent destination brings together all destinations with multilingual content but same location and common banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_destinations', to='products.parentdestination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='when_to_visit_text',
            field=models.TextField(blank=True, help_text='max 6000 characters', max_length=1000, null=True),
        ),
    ]
