# Generated by Django 5.0.1 on 2024-02-02 06:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_destination_getting_around_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='max 255 characters', max_length=255)),
                ('answer', ckeditor.fields.RichTextField(blank=True, help_text='max 3000 characters', max_length=3000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.language')),
                ('parent_destination', models.ForeignKey(blank=True, help_text='The Parent destination brings together all destinations with multilingual content but same location and common banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_destinations', to='products.parentdestination')),
            ],
            options={
                'verbose_name': 'Frequently Asked Questions for Destination',
                'verbose_name_plural': 'Frequently Asked Questions for Destination',
                'db_table': 'faq_destination',
                'ordering': ('parent_destination', 'question'),
            },
        ),
    ]
