# Generated by Django 5.0.1 on 2024-02-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_faqdestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='faqdestination',
            name='priority_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
