# Generated by Django 5.0.1 on 2024-02-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_attraction_faqdestination_priority_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqdestination',
            options={'ordering': ('priority_number',), 'verbose_name': 'Frequently Asked Questions for Destination', 'verbose_name_plural': 'Frequently Asked Questions for Destination'},
        ),
    ]
