# Generated by Django 5.0.1 on 2024-02-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_faqdestination_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attraction',
        ),
    ]
