# Generated by Django 5.0.1 on 2024-02-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_delete_attraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentdestination',
            options={'ordering': ('parent_name',), 'verbose_name_plural': 'Parent Destinations'},
        ),
        migrations.AlterField(
            model_name='faqdestination',
            name='parent_destination',
            field=models.ForeignKey(blank=True, help_text='The Parent destination brings together all destinations with multilingual content but same location and common FAQ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_destinations', to='products.parentdestination'),
        ),
    ]
