# Generated by Django 5.0.1 on 2024-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_parentdestination_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentdestination',
            name='priority_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
