# Generated by Django 5.0.1 on 2024-02-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_parentdestination_priority_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqdestination',
            name='language',
        ),
        migrations.RemoveField(
            model_name='faqdestination',
            name='parent_destination',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='FAQDestination',
        ),
        migrations.DeleteModel(
            name='ParentDestination',
        ),
    ]
