# Generated by Django 5.0.1 on 2024-02-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='media/banners/')),
                ('card_image', models.FileField(blank=True, null=True, upload_to='media/cards/')),
                ('priority_number', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Parent Experiences',
                'ordering': ('parent_name',),
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='parent_experience',
            field=models.ForeignKey(blank=True, help_text='The Parent Experience brings together all experiences with multilingual content but same location and common banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_experiences', to='products.parentexperience'),
        ),
    ]
