# Generated by Django 5.0.1 on 2024-02-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_parentexperience_experience_parent_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='keywords',
            new_name='page_keywords',
        ),
    ]
