# Generated by Django 5.0.1 on 2024-02-06 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_keywords_experience_page_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='price_changed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='price_currency',
            field=models.CharField(blank=True, default='eur', max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_experience_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('adults_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adults_count', models.IntegerField(blank=True, null=True)),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_count', models.IntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=220, null=True)),
                ('stripe_price', models.IntegerField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.experience')),
            ],
        ),
    ]
