# Generated by Django 5.0.1 on 2024-02-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_is_expired_product_is_paid'),
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.event'),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='parentexperience',
            name='parent_name',
            field=models.CharField(db_index=True, max_length=160, unique=True),
        ),
    ]
