# Generated by Django 5.0.1 on 2024-02-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_parentexperience_event_parentexperience_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If this experience is private then to sale whole number of participants as one purchase will be'),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='max_participants',
            field=models.IntegerField(blank=True, default=8, help_text='Maximum number of participants', null=True),
        ),
        migrations.AlterField(
            model_name='parentexperience',
            name='priority_number',
            field=models.IntegerField(blank=True, default=0, help_text='Priority number using for ordering in recommendation queue', null=True),
        ),
        migrations.AlterField(
            model_name='parentexperience',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
