# Generated by Django 5.0.1 on 2024-02-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_experience_meeting_point_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentexperience',
            old_name='price_currency',
            new_name='currency',
        ),
    ]
