# Generated by Django 5.0.1 on 2024-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_rename_price_currency_parentexperience_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='session',
        ),
        migrations.AddField(
            model_name='product',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
