# Generated by Django 5.0.1 on 2024-02-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_parentexperience_child_old_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at', '-total_price')},
        ),
    ]
