# Generated by Django 5.0.1 on 2024-03-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_product_options'),
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants, if 0 then inherit from Parent Experience.', null=True)),
                ('booked_participants', models.IntegerField(blank=True, help_text='Already booked places.', null=True)),
                ('remaining_participants', models.IntegerField(blank=True, help_text='Remaining participants.', null=True)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special price if different from Parent Experience.', max_digits=10, null=True)),
                ('child_special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special child price if different from Parent Experience.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Experience Event',
                'verbose_name_plural': 'Experience Event',
            },
            bases=('schedule.event',),
        ),
    ]
