# Generated by Django 5.0.1 on 2024-03-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_experienceevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentexperience',
            name='event',
        ),
    ]
