# Generated by Django 5.0.1 on 2024-03-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_remove_parentexperience_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceevent',
            options={'verbose_name': 'Experience Event', 'verbose_name_plural': 'Experience Events'},
        ),
    ]
