# Generated by Django 5.0.1 on 2024-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_experienceevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='allowed_languages',
            field=models.ManyToManyField(help_text='list of languages this experience', to='products.language'),
        ),
    ]
