# Generated by Django 5.0.1 on 2024-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_parentexperience_allowed_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceevent',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price for whole private tour.', max_digits=10, null=True),
        ),
    ]
