# Generated by Django 5.0.1 on 2024-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_experienceevent_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentexperience',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="For marketing purposes, this adult old price will be higher than the new one. If it's private - then old total price will be", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parentexperience',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Price for this experience: if it's private then whole total price else - base adult price will be.", max_digits=10),
        ),
    ]
