# Generated by Django 5.0.1 on 2024-03-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_parentexperience_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='If this experience is exclusive then competition will propose.'),
        ),
    ]
