# Generated by Django 5.0.1 on 2024-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_parentexperience_is_exclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='title_for_booking_form',
        ),
        migrations.AddField(
            model_name='experience',
            name='info_subtitle',
            field=models.CharField(blank=True, help_text='Info subtitle above info block, max 255 characters', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='info_title',
            field=models.CharField(blank=True, help_text='Info title above info block, max 120 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='why_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle above why book slider, max 255 characters', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='why_title',
            field=models.CharField(blank=True, help_text='Title above why book slider, max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for the preview card, max 255 characters', max_length=255, null=True),
        ),
    ]
