# Generated by Django 5.0.1 on 2024-03-31 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_experience_recommended_experiences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('name_stop', models.CharField(blank=True, help_text='Name of stop max 160 character length.', max_length=160, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of stop max 320 characters.', max_length=320, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='products.experience')),
            ],
        ),
    ]
