# Generated by Django 5.0.1 on 2024-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_experienceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='schedule_title',
            field=models.CharField(blank=True, help_text='Title for the schedule block in current language, max 120 characters', max_length=120, null=True),
        ),
    ]
