# Generated by Django 5.0.1 on 2024-03-31 12:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_experience_schedule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='includes_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='includes_title',
            field=models.CharField(blank=True, help_text='Title for Includes block in current language, max 120 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='traveler_tips_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='traveler_tips_title',
            field=models.CharField(blank=True, help_text='Title for Traveler tips block in current language, max 120 characters', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='what_to_bring_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='what_to_bring_title',
            field=models.CharField(blank=True, help_text='Title for What to bring block in current language, max 120 characters', max_length=120, null=True),
        ),
    ]
