# Generated by Django 5.0.1 on 2024-03-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_experience_includes_text_experience_includes_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentexperience',
            name='happy_clients_number',
            field=models.IntegerField(default=0),
        ),
    ]
