# Generated by Django 5.0.1 on 2024-04-02 09:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_remove_experience_recommended_experiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), help_text='for example: 4.8', max_digits=2),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='show_on_home_page',
            field=models.BooleanField(default=False, help_text='Include in the top Experiences on the home page'),
        ),
        migrations.AlterField(
            model_name='parentexperience',
            name='meeting_point',
            field=models.ForeignKey(blank=True, help_text='meeting point for this experience', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.meetingpoint', verbose_name='Start location'),
        ),
    ]
