# Generated by Django 5.0.1 on 2024-04-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_parentexperience_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='is_hot_deals',
            field=models.BooleanField(default=False, help_text='If this experience is hot deals will show first queue.'),
        ),
    ]
