# Generated by Django 5.0.1 on 2024-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_parentexperience_is_hot_deals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_recommendations',
            field=models.ManyToManyField(blank=True, to='products.experience'),
        ),
    ]
