# Generated by Django 5.0.1 on 2024-04-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_alter_experience_experience_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='drop_point',
            field=models.ForeignKey(blank=True, help_text='drop point for this experience', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_points', to='products.meetingpoint', verbose_name='Drop off location'),
        ),
        migrations.AlterField(
            model_name='parentexperience',
            name='meeting_point',
            field=models.ForeignKey(blank=True, help_text='meeting point for this experience', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_point', to='products.meetingpoint', verbose_name='Starting location'),
        ),
    ]
