# Generated by Django 5.0.1 on 2024-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_parentexperience_drop_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=models.SlugField(blank=True, help_text='max 255 characters, exactly url tail that is unique', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug generated from name, max 255 characters', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parentexperience',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique, max 255 characters.', max_length=255, unique=True),
        ),
    ]
