# Generated by Django 5.0.1 on 2024-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_experience_slug_alter_meetingpoint_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Category name max 60 characters', max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Category name max 60 characters', max_length=60, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='categories',
            field=models.ManyToManyField(help_text='list of categories this experience', to='products.experiencecategory'),
        ),
    ]
