# Generated by Django 5.0.1 on 2024-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_alter_experiencecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='text_above_calendar',
            field=models.CharField(blank=True, default='Your dates are popular between travelers', help_text='max 60 characters, view above calendar form to hide, make blank', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='clean_and_safe',
            field=models.BooleanField(default=True, help_text='If this experience is clean_and_safe then the corresponding banner appears on the experience page', null=True),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='likely_to_sell_out',
            field=models.BooleanField(default=False, help_text='If this experience is private then it will likely sell the out', null=True),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='recommended_by_locals',
            field=models.BooleanField(default=False, help_text='If this experience is recommended by locals', null=True),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='skip_the_line',
            field=models.BooleanField(default=False, help_text='If this experience is private then it will skip the line', null=True),
        ),
    ]
