# Generated by Django 5.0.1 on 2024-04-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_experience_text_above_calendar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at', '-total_price')},
        ),
    ]
