# Generated by Django 5.0.1 on 2024-04-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Payment', 'Payment'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='experience_images/')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.experience')),
            ],
            options={
                'verbose_name': 'Experience Image',
                'verbose_name_plural': 'Experience Images',
            },
        ),
    ]
