# Generated by Django 5.0.1 on 2024-04-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_alter_product_status_experienceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceimage',
            name='slider_image',
            field=models.FileField(upload_to='experience_images/'),
        ),
    ]
