# Generated by Django 5.0.1 on 2024-04-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_parentexperience_drop_off_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, help_text='Short name max 60 characters', max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Unique, max 60 characters, auto-generated from name if empty field.', max_length=60, unique=True)),
                ('company_name', models.CharField(help_text='Company name max 255 characters', max_length=255, unique=True)),
                ('nif', models.CharField(blank=True, help_text='National Free Identifier, max 60 characters.', max_length=60, null=True, unique=True)),
                ('address', models.CharField(blank=True, help_text='Address line max 255 characters.', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address max 120 characters.', max_length=120, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number max 60 characters.', max_length=60, null=True)),
                ('license', models.CharField(blank=True, help_text='License name max 255 characters.', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='The company provider for current experience', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_provider', to='products.experienceprovider', verbose_name='Provider'),
        ),
    ]
