# Generated by Django 5.0.1 on 2024-04-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_experienceprovider_parentexperience_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceprovider',
            options={'ordering': ('short_name',)},
        ),
    ]
