# Generated by Django 5.0.1 on 2024-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_alter_experienceprovider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='info_title',
            field=models.CharField(blank=True, help_text='Info title above info block, max 160 characters', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='page_description',
            field=models.TextField(blank=True, help_text='SEO page description, max 600 characters', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='page_keywords',
            field=models.TextField(blank=True, help_text='SEO keywords', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='page_title',
            field=models.CharField(blank=True, help_text='SEO title for header in search list, max 120 characters', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='recommendations_slogan',
            field=models.CharField(blank=True, help_text='max 160 characters, belong SEE MORE button', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='recommendations_subtitle',
            field=models.CharField(blank=True, help_text='max 500 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='recommendations_title',
            field=models.CharField(blank=True, help_text='max 255 characters', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for the preview card, max 500 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='why_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle above why book slider, max 500 characters', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='why_title',
            field=models.CharField(blank=True, help_text='Title above why book slider, max 255 characters', max_length=255, null=True),
        ),
    ]
