# Generated by Django 5.0.1 on 2024-04-29 17:49

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_alter_experience_info_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='random_order_number',
            field=models.CharField(blank=True, default=products.models.generate_random_code, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
