# Generated by Django 5.0.1 on 2024-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_product_random_order_number_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='random_order_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
