# Generated by Django 5.0.1 on 2024-04-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_product_random_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='free_cancellation_hours',
            field=models.IntegerField(blank=True, default=24, help_text='How many hours the free cancellation period from payment.', null=True),
        ),
    ]
