# Generated by Django 5.0.1 on 2024-04-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_parentexperience_free_cancellation_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_cancellation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
