# Generated by Django 5.0.1 on 2024-04-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_product_free_cancellation_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='free_cancellation_datetime',
        ),
    ]
