# Generated by Django 5.0.3 on 2024-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_remove_product_free_cancellation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
