# Generated by Django 5.0.3 on 2024-05-08 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_product_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='that_not_bring_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True, verbose_name='That do not bring a block'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='what_to_bring_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True, verbose_name='What to bring block'),
        ),
    ]
