# Generated by Django 5.0.3 on 2024-05-08 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_experience_that_not_bring_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='not_includes_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='List of features NOT INCLUDED in tour, max 1000 characters', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='includes_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='List of features INCLUDED in tour, max 1000 characters', max_length=1000, null=True),
        ),
    ]
