# Generated by Django 5.0.3 on 2024-05-08 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_experience_not_includes_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='that_not_bring_text',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='what_to_bring_text',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='what_to_bring_title',
        ),
        migrations.AddField(
            model_name='experience',
            name='traveler_tips_text_2',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Max 1000 characters, NEGATIVE LIST', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='traveler_tips_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Max 1000 characters, POSITIVE LIST', max_length=1000, null=True),
        ),
    ]
