# Generated by Django 5.0.3 on 2024-05-08 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_remove_experience_that_not_bring_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='traveler_tips_text_2',
        ),
        migrations.AlterField(
            model_name='experience',
            name='traveler_tips_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Max 1000 characters', max_length=1000, null=True),
        ),
    ]
