# Generated by Django 5.0.3 on 2024-05-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0079_alter_parentexperience_priority_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentexperience',
            options={'ordering': ('-priority_number',), 'verbose_name_plural': 'Parent Experiences'},
        ),
    ]
