# Generated by Django 5.0.3 on 2024-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_alter_parentexperience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='second_purchase_discount',
            field=models.PositiveSmallIntegerField(blank=True, default=20, help_text='Secondary purchase discount in EUR from price for secondary products', null=True),
        ),
    ]
