# Generated by Django 5.0.3 on 2024-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0084_alter_product_options_product_price_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='hotel_pick_up',
            field=models.BooleanField(default=False, help_text='If this experience has hotel pick up service.'),
        ),
    ]
