# Generated by Django 5.0.3 on 2024-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_parentexperience_hotel_pick_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencecategory',
            name='card_image',
            field=models.FileField(blank=True, null=True, upload_to='media/cards/'),
        ),
        migrations.AddField(
            model_name='experiencecategory',
            name='card_image_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/cards/'),
        ),
        migrations.AddField(
            model_name='experienceimage',
            name='slider_image_mobile',
            field=models.FileField(blank=True, null=True, upload_to='experience_images/'),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='banner_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/banners/'),
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='card_image_mobile',
            field=models.FileField(blank=True, null=True, upload_to='media/cards/'),
        ),
    ]
