# Generated by Django 5.0.3 on 2024-06-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_alter_experienceschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentexperience',
            name='allowed_options',
            field=models.ManyToManyField(help_text='Options for this experience', to='products.experienceoption'),
        ),
    ]
