# Generated by Django 5.0.3 on 2024-06-04 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_parentexperience_allowed_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience_option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.experienceoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
            options={
                'ordering': ['experience_option'],
                'unique_together': {('product', 'experience_option')},
            },
        ),
    ]
