# Generated by Django 5.0.3 on 2024-06-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0090_alter_productoption_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='max_quantity',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
