# Generated by Django 5.0.3 on 2024-06-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0091_productoption_max_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentexperience',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='parentexperience',
            name='banner_mobile',
        ),
        migrations.RemoveField(
            model_name='parentexperience',
            name='happy_clients_number',
        ),
        migrations.RemoveField(
            model_name='parentexperience',
            name='rating',
        ),
    ]
