# Generated by Django 5.0.3 on 2024-06-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_remove_parentexperience_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='max_quantity',
        ),
        migrations.AddField(
            model_name='experienceoption',
            name='max_quantity',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
