# Generated by Django 5.0.3 on 2024-06-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0093_remove_productoption_max_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceoption',
            options={'ordering': ('-priority_number',), 'verbose_name': 'Option Extras', 'verbose_name_plural': ('Options Extras',)},
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='we_care_about_comfort',
            field=models.BooleanField(default=False, help_text='If this experience is our own then it will cause the comfort.', null=True),
        ),
    ]
