# Generated by Django 5.0.3 on 2024-06-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_alter_experienceoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceoption',
            options={'ordering': ('-priority_number',), 'verbose_name': 'Option Extras', 'verbose_name_plural': 'Options Extras'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created_at', 'ordering': ('created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['experience_option'], 'verbose_name': 'Order Option', 'verbose_name_plural': 'Order Options Extras'},
        ),
    ]
