# Generated by Django 5.0.3 on 2024-06-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0096_alter_experienceoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Product random number.', max_length=255, null=True)),
                ('url', models.URLField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='products.product')),
            ],
        ),
    ]
