# Generated by Django 5.0.3 on 2024-06-17 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0097_productqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 8, 19, 22, 54400, tzinfo=datetime.timezone.utc)),
        ),
    ]
