# Generated by Django 5.0.3 on 2024-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0099_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Time of day name max 60 characters', max_length=60, unique=True)),
                ('description', models.CharField(blank=True, help_text='Time of day description max 255 characters', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='time_of_day',
            field=models.ManyToManyField(help_text='list of titme of day variables', to='products.timeofday'),
        ),
    ]
