# Generated by Django 5.0.3 on 2024-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0100_timeofday_parentexperience_time_of_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationForExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Duration name max 60 characters', max_length=60, unique=True)),
                ('description', models.CharField(blank=True, help_text='Duration description max 255 characters', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='parentexperience',
            name='duration',
            field=models.ManyToManyField(help_text='list of duration types', to='products.durationforexperience'),
        ),
    ]
