# Generated by Django 5.0.3 on 2024-06-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0101_durationforexperience_parentexperience_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='durationforexperience',
            options={'ordering': ('name',)},
        ),
    ]
