# Generated by Django 5.0.3 on 2024-06-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0102_alter_durationforexperience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='stripe_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
