# Generated by Django 5.0.3 on 2024-06-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0103_productoption_stripe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceevent',
            name='rule_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_rule_events', to='products.experienceevent'),
        ),
        migrations.AddField(
            model_name='experienceevent',
            name='stop_rule_date',
            field=models.DateField(blank=True, help_text='Date of stop rule.', null=True),
        ),
        migrations.AlterField(
            model_name='experienceevent',
            name='child_special_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special child price if different from Parent Experience.', max_digits=10, null=True, verbose_name='Child Price (Group)'),
        ),
        migrations.AlterField(
            model_name='experienceevent',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special price if different from Parent Experience.', max_digits=10, null=True, verbose_name='Adult Price (Group)'),
        ),
        migrations.AlterField(
            model_name='experienceevent',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price for whole private tour.', max_digits=10, null=True, verbose_name='Total Price (Private)'),
        ),
    ]
